### ISSUE TITLE
no such method "unpack()" in Message class

### ISSUE THREAD

**Issue by max1gu** [dstucrypt/jkurwa#19]
https://github.com/dstucrypt/jkurwa/blob/679fb247054aa61c4088043d78114b27bc7e041b/examples/decrypt.js#L19

**Comment by muromec** [comment]
Please disregard this example, as it should be removed or updated. Please refer to `test/test-box.js` and agent repo to see how messages could be decrypted.

**Comment by muromec** [comment]
@max1gu please confirm if 5909ad7b056 fixes it for you.
